exports.generateSummary = async (data) => {
    // This function Mock integration with an LLM.
    // In a real scenario, we would send 'data' to OpenAI/Gemini API.

    const { availability, lighthouse, accessibility, security, links, extended } = data;

    let score = 0;
    let suggestions = [];
    let strengths = [];

    // --- Scoring Logic ---
    if (availability.up) score += 10;

    // Performance (Heavy weight)
    const perfScore = lighthouse?.categories?.performance?.score * 100 || 0;
    score += (perfScore * 0.3);
    if (perfScore < 50) suggestions.push("Critical: Load speed is very slow. Optimize images (WebP), defer offscreen images, and minify JS/CSS.");
    else if (perfScore >= 90) strengths.push("Performance is world-class! The site loads instantly.");

    // Accessibility
    const violations = accessibility?.violations?.length || 0;
    const a11yScore = lighthouse?.categories?.accessibility?.score * 100 || 100; // Use Lighthouse score preferably
    score += (a11yScore * 0.2);
    if (violations > 0) suggestions.push(`Accessibility: Found ${violations} specific violations (e.g. missing alt tags, poor contrast). Fix these to improve inclusivity.`);
    else strengths.push("Accessibility compliance is excellent.");

    // Security
    if (security.https) {
        score += 10;
        strengths.push("Security: HTTPS is correctly enabled.");
    } else {
        suggestions.push("Security Critical: HTTPS is missing! This severely impacts trust and SEO.");
    }

    const missingHeaders = Object.keys(security?.headers || {}).filter(h => security.headers[h] === 'Missing');
    if (missingHeaders.length > 2) suggestions.push("Security: Modern security headers (CSP, HSTS) are missing. Add them to prevent XSS/Clickjacking.");

    // SEO
    const seoScore = lighthouse?.categories?.seo?.score * 100 || 0;
    score += (seoScore * 0.15);

    // Discovery & Standards (Extended)
    if (extended) {
        if (extended.files?.robots) score += 5;
        else suggestions.push("SEO: Robots.txt not found. Search engines use this to crawl your site efficiently.");

        if (extended.files?.sitemap) score += 5;
        else suggestions.push("SEO: Sitemap.xml missing. A sitemap helps engines index your pages correctly.");

        if (extended.seoTags?.description === 'Missing') suggestions.push("SEO: Meta description is missing. This impacts click-through rates from search results.");
        if (!extended.socialMedia?.ogTitle) suggestions.push("Social: OpenGraph tags are missing. Your site won't look professional when shared on social media.");

        if (extended.compression !== 'None') score += 5;
        else suggestions.push("Performance: Text compression (Gzip/Brotli) is disabled explicitly.");
    }

    // Links
    if (links) {
        if (links.brokenLinks && links.brokenLinks.length > 0) {
            suggestions.push(`Quality Assurance: Found ${links.brokenLinks.length} broken links. These frustrate users and hurt SEO.`);
        } else {
            score += 5;
        }
    }

    // Cap score at 100
    score = Math.min(100, Math.round(score));

    // --- Generate Text ---
    let summary = `## 🤖 AI Executive Summary\n\n`;

    summary += `**Overall Health Score: ${score}/100**\n\n`;

    if (score >= 90) {
        summary += "The analyzed website demonstrates **exceptional technical health**. It excels in performance and accessibility, providing a top-tier user experience. Minor optimizations may still be possible, but the foundation is rock solid.\n";
    } else if (score >= 70) {
        summary += "The website is in **good condition** but has specific areas for improvement. While fundamental security and performance metrics are met, there is room to optimize load times and accessibility compliance to reach elite standards.\n";
    } else if (score >= 50) {
        summary += "The website shows **average performance**. Several critical issues in performance or security were detected that may be impacting user retention and search engine ranking. Immediate attention to the recommendations below is advised.\n";
    } else {
        summary += "The website requires **urgent attention**. Multiple critical failures in security, stability, or performance were detected. These issues likely result in a poor user experience and significant traffic loss.\n";
    }

    if (strengths.length > 0) {
        summary += "\n### ✅ Key Strengths\n";
        strengths.slice(0, 3).forEach(s => summary += `- ${s}\n`);
    }

    if (suggestions.length > 0) {
        summary += "\n### 🚀 High-Priority Recommendations\n";
        suggestions.slice(0, 5).forEach(s => summary += `- ${s}\n`);
    } else {
        summary += "\n### 🚀 Recommendations\n- Continue monitoring uptime and performance periodically.\n";
    }

    summary += "\n---\n*Generated by Web Test AI Engine*";

    return {
        text: summary,
        score
    };
};
